from typing import *


class Plan:
    """represent the plan generated by llm from user request"""

    def __init__(self, plan_p:str):
        self.planP: str = plan_p
        self.userP: str | None = None
        self.plan = None
        self.first_prompt = True

    def prompt(self, user_p:str| None, local_model_tools: str|None = None) -> str:
        self.userP = user_p
        return self.planP.format(local_model_tools or "None", self.userP or "")

    def is_first_prompt(self):
        return self.first_prompt

    def set_plan(self,plan:str):
        self.plan = plan

    def get_plan(self):
        return self.plan

    def parse_plan(self):
        """parsing the plan into a savable format"""
        pass







