import consts
class Plan:
    """represent the plan generated by llm from user request"""

    def __init__(self):
        self.userP: str | None = None
        self.plan = None
        self.first_prompt = True

    def prompt(
        self,
        user_p: str | None,
        local_model_tools: str | None = None,
        frontier_tools: str | None = None,
        local_model_profile: str | None = None,
    ) -> str:
        self.userP = user_p
        self.first_prompt = False

        return (
            consts.PLAN_PROMPT
            .replace("__USER_REQUEST__", self.userP or "")
            .replace("__LOCAL_TOOLS__", local_model_tools or "None")
            .replace("__FRONTIER_TOOLS__", frontier_tools or "None")
            .replace(
                "__LOCAL_MODEL_PROFILE__",
                local_model_profile or (
                    "Unknown local model. Assume it is weaker than the frontier model "
                    "and needs clear atomic instructions."
                ),
            )
        )

    def is_first_prompt(self):
        return self.first_prompt

    def set_plan(self, plan: str):
        self.plan = plan

    def get_plan(self):
        return self.plan

    def parse_plan(self):
        """parsing the plan into a savable format"""
        pass